### ISSUE TITLE
Generate a machine-local go.work so sibling worktrees stop emitting phantom diagnostics

### ISSUE THREAD

**Issue by sydlexius** [sydlexius/stillwater#3047]
## Summary

Sibling worktrees are invisible to the Go language server, so any editor that opens a file inside one reports it as outside the workspace and then emits a cascade of bogus `undefined:` errors for symbols that resolve perfectly well when that worktree is built on its own.

A representative burst, from a file in `../stillwater-3037-bulkrestore`:

```
handlers_blast_radius_restore.go:
  [Line 168] use of internal package github.com/sydlexius/stillwater/internal/artist not allowed (go list)
  [Line 350] undefined: Router [UndeclaredName] (compiler)
  [Line 354] undefined: writeJSON [UndeclaredName] (compiler)
  ...
  [Line 1:9] This file is within module "../stillwater-3037-bulkrestore", which is not
             included in your workspace. To fix this problem, you can add a go.work file
             that uses this directory.
```

None of it is real. `go build`, `go vet ./...` and the full pre-push gate all pass inside each worktree. gopls is resolving against the main checkout's module and finding nothing.

## Why it is worth fixing

The repo's own workflow makes this constant rather than occasional. `make worktree` is the documented way to work an issue, `docs/worktrees.md` describes running several at once, and a milestone drain routinely has four to seven open at a time. Every one of them is a noise generator the moment a file inside it is opened.

The cost is not just clutter. Real diagnostics arrive in the same channel, so a genuine compile error in the main checkout has to be picked out of a wall of `undefined: Router`. That is a signal-to-noise problem, and the standard failure mode is that the reader stops reading the channel.

The last line of gopls' own message names the fix.

## Proposed change

Generate a machine-local `go.work` that lists the main checkout plus every live sibling worktree, maintained by the same targets that already manage worktrees.

- `make worktree` regenerates it after adding a worktree.
- `make remove-worktree` regenerates it after removing one.
- Add `go.work` and `go.work.sum` to `.gitignore`.

There is precedent for the shape: `make worktree` already calls `scripts/link-worktree-settings.sh` to wire a machine-local, gitignored file into each new worktree, so a per-machine artifact maintained by the worktree targets is an established pattern here rather than a new one.

Regenerating from `git worktree list` on each add and remove keeps the file honest without a manual step. A worktree removed outside the make target leaves a stale entry, which `go work use` tolerates but which is worth a note in `docs/worktrees.md`.

## Acceptance criteria

- [ ] Opening a Go file inside a sibling worktree produces no "not included in your workspace" diagnostic and no spurious `undefined:` cascade.
- [ ] `go.work` and `go.work.sum` are gitignored; `git status` is clean after `make worktree` and after `make remove-worktree`.
- [ ] `make worktree` and `make remove-worktree` both leave `go.work` listing exactly the worktrees `git worktree list` reports.
- [ ] The pre-push gate, `go vet ./...`, and `go build ./...` behave identically in the main checkout and in a worktree, with and without the file present.
- [ ] A worktree removed by raw `git worktree remove` (outside the make target) does not break the build; the documented recovery is stated in `docs/worktrees.md`.

## Notes

Worth confirming during implementation rather than assuming:

- Whether `go.work` changes what the pre-push gate or CI resolves. CI checks out a single tree and never has sibling worktrees, so the file should be absent there entirely, but the gate runs locally where it will be present. Verify the gate produces the same verdict either way.
- Whether any tooling in `scripts/` walks the module graph in a way a workspace file would alter.
- Whether `go.work.sum` gets written at all with all modules being the same module; if it does not, gitignoring it is harmless.

[mode: direct][model: sonnet][effort: low]
